###
# image docs: https://github.com/bitnami/bitnami-docker-kafka
# 
# consumer:
#     kafka-console-consumer.sh --bootstrap-server kafka-us:9092 --topic test --from-beginning
#
# producer:
#     kafka-console-producer.sh --bootstrap-server  kafka-us:9092 --topic test
###
version: "2"

services:
  zookeeper-us:
    image: docker.io/bitnami/zookeeper:3.7
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  
  zookeeper-eu:
    image: docker.io/bitnami/zookeeper:3.7
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-us:
    image: docker.io/bitnami/kafka:3
    ports:
      - "9192:9092"
    # volumes:
      # - "./config-us:/bitnami/kafka/config"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-us:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9192
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka-us:9092,EXTERNAL://localhost:9192
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper-us

  kafka-eu:
    image: docker.io/bitnami/kafka:3
    # volumes:
      # - "./config-eu:/bitnami/kafka/config"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-eu:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-eu

  # producer:
  #   image: docker.io/bitnami/kafka:3
  #   environment:
  #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-us:2181
  #   command: "tail -f /dev/null"
  #   depends_on:
  #     - kafka-us
  #     - kafka-eu
  
  consumer:
    image: docker.io/bitnami/kafka:3
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-us:2181
    command: "kafka-console-consumer.sh --bootstrap-server kafka-us:9092 --topic test --from-beginning"
    depends_on:
      - kafka-us
      - kafka-eu
  
  # busybox:
  #   image: busybox:latest
  #   command: "tail -f /dev/null"