version: "2"

services:
  zookeeper-us:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  
  zookeeper-eu:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2182:2182"
    environment:
      - ZOO_PORT_NUMBER=2182
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-us:
    image: docker.io/bitnami/kafka:3
    ports:
      - "9092:9092"
    # volumes:
    #   - "./server.properties-us:/bitnami/kafka/config/server.properties"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-us:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-us

  kafka-eu:
    image: docker.io/bitnami/kafka:3
    ports:
      - "9093:9092"
    # volumes:
    #   - "./server.properties-eu:/bitnami/kafka/config/server.properties"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-eu:2182
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-eu
  
  # client:
  #   image: docker.io/bitnami/kafka:3
  #   hostname: "client"
  #   environment:
  #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #   depends_on:
  #     - zookeeper
  
  busybox:
    image: busybox:latest
    command: "tail -f /dev/null"